
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad_javamysql;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MiguelPerezUSB
 */
public class Frmnotas extends javax.swing.JFrame {

    /**
     * Creates new form Frmnotas
     */
    public Frmnotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblcodalu = new javax.swing.JLabel();
        lblcodmat = new javax.swing.JLabel();
        lblnota1 = new javax.swing.JLabel();
        lblnota2 = new javax.swing.JLabel();
        lblnota3 = new javax.swing.JLabel();
        lblnotafinal = new javax.swing.JLabel();
        txtcodalu = new javax.swing.JTextField();
        txtcodmat = new javax.swing.JTextField();
        txtnota1 = new javax.swing.JTextField();
        txtnota2 = new javax.swing.JTextField();
        txtnota3 = new javax.swing.JTextField();
        txtnotafinal = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnotas = new javax.swing.JTable();

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcodalu.setText("Codigo Alumno: ");

        lblcodmat.setText("Codigo Materia: ");

        lblnota1.setText("Primera Nota: ");

        lblnota2.setText("Segunda Nota: ");

        lblnota3.setText("Tercera Nota: ");

        lblnotafinal.setText("Nota Final: ");

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        tblnotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CodigoAlumno", "CodigoMateria", "PrimeraNota", "SegundaNota", "TerceraNota", "NotaFinal"
            }
        ));
        jScrollPane2.setViewportView(tblnotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcodmat)
                                    .addComponent(lblnota1)
                                    .addComponent(lblnota2)
                                    .addComponent(lblnota3)
                                    .addComponent(lblnotafinal)
                                    .addComponent(lblcodalu, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodalu)
                                    .addComponent(txtcodmat)
                                    .addComponent(txtnota1)
                                    .addComponent(txtnota2)
                                    .addComponent(txtnota3)
                                    .addComponent(txtnotafinal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btninsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninsertar)
                    .addComponent(lblcodalu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodmat)
                    .addComponent(txtcodmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnota1)
                    .addComponent(txtnota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnota2)
                    .addComponent(txtnota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnota3)
                    .addComponent(txtnota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalir)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnotafinal)
                    .addComponent(txtnotafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
                 conectar cc = new conectar();
        Connection cn = cc.conexion();
        String codalu,codmat,nota1,nota2,nota3,notaf;
        String sql= "";
        codalu= txtcodalu.getText();
        codmat= txtcodmat.getText();
        nota1 = txtnota1.getText();
        nota2 = txtnota2.getText();
        nota3 = txtnota3.getText();
        notaf = txtnotafinal.getText();
        sql = "insert into tblnotas (codigoalu,codigomat,nota1,nota2,nota3,notafinal) values (?,?,?,?,?,?)";
         try {
             PreparedStatement pst = cn.prepareStatement(sql);
             pst.setString(1,codalu);
             pst.setString(2,codmat);
             pst.setString(3,nota1);
              pst.setString(4,nota2);
              pst.setString(5,nota3);
               pst.setString(6,notaf);
             int registro=pst.executeUpdate();
             if (registro>0)
             {
                 JOptionPane.showMessageDialog(null, "Registro almacenado correctamente");
                 limpiar();
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Registro NO almacenado " + e.getMessage());

    }  
    }                                           

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
                         conectar cc = new conectar();
        Connection cn = cc.conexion();
        String codalu,codmat,nota1,nota2,nota3,notaf;
        String sql ="";
        codalu= txtcodalu.getText();
        codmat= txtcodmat.getText();
        nota1 = txtnota1.getText();
        nota2 = txtnota2.getText();
        nota3 = txtnota3.getText();
        notaf = txtnotafinal.getText();
        sql = "update tblnotas SET "
            + "codigoalu= '"+codalu+"', "
            + "codigomat= '"+codmat+"', "
            + "nota1=  '"+nota1+"' , "
            + "nota2=  '"+nota2+"' , "
            + "nota3=  '"+nota3+"' , "
            + "notafinal= '"+notaf+"'"    
            + "WHERE codigomat= '"+codmat+"'";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro actualizado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para actualizar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO actualizado" + e.getMessage());
        }
    }                                             

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
                 conectar cc = new conectar();
        Connection cn = cc.conexion();
        String codalu,codmat,nota1,nota2,nota3,notaf;
        String sql ="";
        codalu= txtcodalu.getText();
        codmat= txtcodmat.getText();
        nota1 = txtnota1.getText();
        nota2 = txtnota2.getText();
        nota3 = txtnota3.getText();
        notaf = txtnotafinal.getText();
        sql = "DELETE from tblnotas  "
            + "WHERE codigoalu= '"+codalu+"'";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro eliminado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para eliminar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO eliminado" + e.getMessage());
        }
    }                                           

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String codalu,codmat,nota1,nota2,nota3,notaf;
        String sql="";
        codalu= txtcodalu.getText();
        codmat= txtcodmat.getText();
        nota1 = txtnota1.getText();
        nota2 = txtnota2.getText();
        nota3 = txtnota3.getText();
        notaf = txtnotafinal.getText();
        sql = "SELECT * FROM tblnotas "
            + "WHERE codigoalu= '"+codalu+"'";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblnotas.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }                                         

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Cerrar();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmnotas().setVisible(true);
            }
        });
    }
    public void limpiar()
    {
        txtcodalu.setText("");
        txtcodmat.setText("");
        txtnota1.setText("");
        txtnota2.setText("");
        txtnota3.setText("");
        txtnotafinal.setText("");
    }
    public void Cerrar(){
    super.dispose();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodalu;
    private javax.swing.JLabel lblcodmat;
    private javax.swing.JLabel lblnota1;
    private javax.swing.JLabel lblnota2;
    private javax.swing.JLabel lblnota3;
    private javax.swing.JLabel lblnotafinal;
    private javax.swing.JTable tblnotas;
    private javax.swing.JTextField txtcodalu;
    private javax.swing.JTextField txtcodmat;
    private javax.swing.JTextField txtnota1;
    private javax.swing.JTextField txtnota2;
    private javax.swing.JTextField txtnota3;
    private javax.swing.JTextField txtnotafinal;
    // End of variables declaration                   
}
